### ISSUE TITLE
Adding Songs to Spotify Playlist from Saved Page

### ISSUE THREAD

**Issue by bumigumi** [lucyzhang04/326Project#155]
Adding songs on Saved page to a chosen Spotify Playlist using dropdown similar to #151, except the button is "Add to Playlist" instead of "Like"

**Comment by saadhvir** [comment]
If we add this, are we going to remove the current playlist addition functionality from the trending page? I think it might be a bit confusing if we have the same feature in two different places.

**Comment by bumigumi** [comment]
Hi! Yes, I am deleting the playlist addition functionality from the trending page since the UI there is probably confusing and unintuitive. Making an issue and PR for that shortly.
