### ISSUE TITLE
Implement Sequelize interface for SQLite DB instance + create submissions table schema

### ISSUE THREAD

**Issue by nehaka02** [lucyzhang04/326Project#74]
**Description:** This will follow the structure presented in Tasks V5. This feature will be implemented in the persistent_submissions branch. The primary components of this feature are three files. SQLiteModel.js, which imports the Sequelize library, defines the Submissions table schema, and defines CRUD operations on the Submissions table. ModelFactory.js provides the abstraction to utilize multiple DB models if necessary. SubmissionControler.js contains high-level methods to invoke CRUD operations on the submissions table. The goal of this feature is to provide persistent storage for songs to service the Feed, Trending, and History pages.
**Tag:** #74
**Owner:** Neha Aryasomayajula
**Expected Outcome:** Fully usable Sequelize abstraction for SQLite database instance, functional Submissions table schema, CRUD methods for Submissions table.

**Comment by lucyzhang04** [comment]
Looks like this has been successfully completed! Closing the issue.
