### ISSUE TITLE
Implement History Page DB Queries

### ISSUE THREAD

**Issue by nehaka02** [lucyzhang04/326Project#96]
**Description:** Implement two queries in the SQLite model: the first query retrieves all past submissions associated with a particular username, and the second query retrieves  a quote associated with a particular submission date. These two queries will be used to service a table in the frontend that shows a user's past submissions along with their associated quotes. 
**Tag:**  #96
**Owner:** Neha Aryasomayajula
**Expected outcome:** Working queries that retrieve submissions associated with a username and quotes associated with a particular date.

**Comment by saadhvir** [comment]
This is fully functional for me -- the history page shows all of my past submissions and their associated quotes, so the queries are working correctly.

**Comment by MShvakel** [comment]
Neha's implementation is functional! When I look at the history page, I am able to see my past song submissions, the artist, and the quote of the day.
