### ISSUE TITLE
Set Up API Integration for Fetching Quotes

### ISSUE THREAD

**Issue by cynthiaraj501** [lucyzhang04/326Project#97]
Set Up API Integration for Fetching Quotes (Quotes API Integration "sub-feature")

- Description: Modified loadQuote() function in index.html to fetch quotes from an API. Utilize `fetch` method to get daily quote data.
- Tag: #95 
- Owner: Cynthia
- Expected Outcome: Application should utilize API for quote generation, as opposed to prior implementation with mocked quote data; the quote should be successfully fetched and displayed.

**Comment by MShvakel** [comment]
I tested Cynthia's implementation, and the API works appropriately to fetch a new quote daily!
