### ISSUE TITLE
Set Up CORS Middleware

### ISSUE THREAD

**Issue by cynthiaraj501** [lucyzhang04/326Project#98]
Set Up CORS Middleware (Quotes API Integration "sub-feature")

- Description: Add middleware to handle CORS issues for API requests.
- Tag: #95 
- Owner: Cynthia
- Expected Outcome: Application should be able to successfully utilize API for quote generation (no CORS errors).

**Comment by nehaka02** [comment]
I believe the CORS bugs we were experiencing are now fixed-- looks good to me!
